# Puerto del servidor
server.port=8082
spring.application.name=rednorte-ms-citas

# Configuración de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/db_citas
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect